WebAuto/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor', include('ckeditor_uploader.urls')),
    path('', include("CarShowroom.urls")),
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    path('', include("CarShowroom.urls")),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    #urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

CarShowroom/models.py
import datetime

from django.db import models
from pyexpat import model

from django.urls import reverse

from ckeditor_uploader.fields import RichTextUploadingField


class StaticInfo(models.Model):
    # Главная страница
    name = models.CharField(max_length=200, default='')
    sliderInfo = RichTextUploadingField()

    expYears = models.PositiveSmallIntegerField('Лет опыта')
    workers = models.PositiveSmallIntegerField('Кол-во работников')
    dovrelnyClients = models.PositiveIntegerField('Кол-во клиентов')

    electroCarPicture = models.ImageField('Картинка электромобиля')
    electroCarInfo = RichTextUploadingField()

    discountSection = RichTextUploadingField()

    development = models.TextField()
    trust = models.TextField()
    guarantees = models.TextField()

    address = models.CharField(max_length=250)
    phone = models.CharField(max_length=50)
    workTime = models.CharField(max_length=250)

    def __str__(self):
        return f"{self.name}"

    class Meta:
        verbose_name = "Глав. страница"
        verbose_name_plural = "Глав. страницы"


class Product(models.Model):
    # Деталь для авто
    name = models.CharField('Название', max_length=200)
    description = models.TextField('Описание')
    price = models.PositiveIntegerField("Цена")
    picture = models.TextField("Изображение")
    rating = models.PositiveSmallIntegerField("Рейтинг", default=0)
    slug = models.SlugField(max_length=160, unique=True)

    def get_absolute_url(self):
        return reverse("product_page", kwargs={"slug": self.slug})

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Деталь"
        verbose_name_plural = "Детали"


class Reviews(models.Model):
    # Отзывы
    text = models.TextField("Отзыв")
    name = models.CharField('Имя', max_length=200)
    mail = models.EmailField('Почта')
    date = models.DateTimeField('Дата публикации', null=True)
    rating = models.PositiveSmallIntegerField('Рейтинг отзыва', default=3)
    product = models.ForeignKey(Product, verbose_name='Товар', on_delete=models.CASCADE, null=True)

    def __str__(self):
        return f"{self.name} - {self.product}"

    class Meta:
        verbose_name = "Отзыв"
        verbose_name_plural = "Отзывы"


class TestDrive(models.Model):
    # Записи на тест драйв
    name = models.CharField('Имя', max_length=200)
    surname = models.CharField('Фамилия', max_length=200)
    mail = models.EmailField('Почта')
    phone = models.CharField('Телефон', max_length=100)
    car_model = models.CharField('Модель авто', max_length=100)
    time = models.CharField('Время', max_length=50)
    date = models.DateTimeField('Дата')
    send_data = models.DateTimeField('Дата отправки заявки', default=None)

    def __str__(self):
        return f"{self.name} - {self.car_model}"

    class Meta:
        verbose_name = "Запись на тест драйв"
        verbose_name_plural = "Записи на тест драйв"


class Engine(models.Model):
    title = models.CharField('Название', max_length=200)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Двигатель"
        verbose_name_plural = "Двигатели"


class Drive(models.Model):
    title = models.CharField('Название', max_length=200)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Привод"
        verbose_name_plural = "Приводы"


class Transmission(models.Model):
    title = models.CharField('Название', max_length=200)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Коробка передач"
        verbose_name_plural = "Коробки передач"


class Modeltype(models.Model):
    title = models.CharField('Название', max_length=200)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Тип модели"
        verbose_name_plural = "Типы моделей"


class Car(models.Model):
    model = models.CharField('Модель', max_length=100)
    line = models.CharField('Линейка', max_length=100, default='', blank=True)
    price = models.CharField('Цена', max_length=100)
    poster = models.ImageField('Глав. изображение')
    slug = models.SlugField('slug', max_length=200, default='')

    tagline = models.CharField('Слоган', max_length=200, default='')
    description = models.TextField('Описание', default='')

    about_design = models.TextField('Про дизайн', default='', blank=True)
    about_comfort = models.TextField('Про комфорт', default='', blank=True)
    about_controllability = models.TextField('Про управляемость', default='', blank=True)

    feature_number1 = models.CharField('Число первой особенности', max_length=150, default='')
    feature_text1 = models.CharField('Текст первой особенности', max_length=150, default='')
    feature_number2 = models.CharField('Число второй особенности', max_length=150, default='')
    feature_text2 = models.CharField('Текст второй особенности', max_length=150, default='')
    feature_number3 = models.CharField('Число третей особенности', max_length=150, default='')
    feature_text3 = models.CharField('Текст третей особенности', max_length=150, default='')

    power = models.CharField('Мощность', max_length=100, default='')
    number_of_packages = models.CharField('Количество мест', max_length=100, default='')

    model_type = models.ForeignKey(Modeltype, on_delete=models.CASCADE, verbose_name='Тип модели', default='')
    engine = models.ForeignKey(Engine, on_delete=models.CASCADE, verbose_name='Двигатель', default='')
    drive = models.ForeignKey(Drive, on_delete=models.CASCADE, verbose_name='Привод', default='')
    transmission = models.ForeignKey(Transmission, on_delete=models.CASCADE, verbose_name='Коробка передач', default='')

    acceleration = models.CharField('Разгон', max_length=100, default='')
    max_speed = models.CharField('Максимальная скорость', max_length=100, default='')

    def get_absolute_url(self):
        return reverse("car_detail_view", kwargs={"slug": self.slug})

    def __str__(self):
        return f"AUDI {self.model} {self.line}"

    class Meta:
        verbose_name = "Автомобиль"
        verbose_name_plural = "Автомобили"


class CarImages(models.Model):
    imageSlider1 = models.ImageField('Картинка для слайдера 1')
    imageSlider2 = models.ImageField('Картинка для слайдера 2')
    imageSlider3 = models.ImageField('Картинка для слайдера 3')

    imageAbout1 = models.ImageField('Дизайн')
    imageAbout2 = models.ImageField('Комфорт')
    imageAbout3 = models.ImageField('Управляемость')

    imageGallery1 = models.ImageField('Картинка для галереи 1')
    imageGallery2 = models.ImageField('Картинка для галереи 2')
    imageGallery3 = models.ImageField('Картинка для галереи 3')
    imageGallery4 = models.ImageField('Картинка для галереи 4')
    imageGallery5 = models.ImageField('Картинка для галереи 5')
    imageGallery6 = models.ImageField('Картинка для галереи 6')

    car = models.ForeignKey(Car, on_delete=models.CASCADE, verbose_name='Автомобиль', default=0)

    def __str__(self):
        return f"AUDI picture {self.car}"

    class Meta:
        verbose_name = "Галерея"
        verbose_name_plural = "Галереи"


class PurchaseCar(models.Model):
    # Запрос к дилеру

    car_model = models.CharField('Модель авто', max_length=200)
    name = models.CharField('Имя', max_length=200)
    surname = models.CharField('Фамилия', max_length=200)
    mail = models.EmailField('Почта')
    phone = models.CharField('Телефон', max_length=100)
    date = models.DateTimeField('Дата записи', default=datetime.datetime.now())

    def __str__(self):
        return f"{self.car_model} - {self.name} - {self.surname}"

    class Meta:
        verbose_name = "Запрос к дилеру"
        verbose_name_plural = "Запросы к дилеру"


class ServiceCar(models.Model):
    # Заявка на сервис

    work_type = models.CharField('Модель авто', max_length=200)
    name = models.CharField('Имя', max_length=200)
    surname = models.CharField('Фамилия', max_length=200)
    mail = models.EmailField('Почта')
    phone = models.CharField('Телефон', max_length=50)
    time = models.CharField('Время', max_length=50)
    date = models.DateTimeField('Дата записи')
    date_send = models.DateTimeField('Дата отправки заявки', default=datetime.datetime.now())

    def __str__(self):
        return f"{self.work_type} - {self.name} - {self.surname}"

    class Meta:
        verbose_name = "Заявка на сервис"
        verbose_name_plural = "Заявки на сервис"

templates/ThxRecordTestDrive.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
<section>
    <div class="container">
        <div class="col-lg-12">
            <h3 style="margin-top: 30px">{% trans 'Вы были записаны на тест-драйв' %}</h3>
            <h4 style="margin-bottom: 30px">{% trans 'Проверьте вашу почту чтобы узнать подробности.' %}</h4>
        </div>
    </div>
</section>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
{% load i18n %}
{% load static %}

<html lang="ru">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'style/animate.css' %}">
    <link rel="stylesheet" href="{% static 'style/style.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@300;400;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'style/font-awesome-4.7.0/css/font-awesome.min.css' %}">

    <title>{% block title %}{% trans 'Автосалон' %} AUDI Store{% endblock title %}</title>
</head>
<body>

    {% block header %}
        {% include 'include/header.html' %}
    {% endblock header %}

    {% block content %}

    {% endblock content %}

    {% include 'include/pop-out-menu.html' %}
    {% include 'include/footer.html' %}


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="{% static 'js/main.js' %}"></script>

</body>
</html>

templates/cars.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block content %}
<section>
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="car-top-info">
                    <h3>
                        {% trans 'Ваше дополнительное преимущество до 280 000 рублей.' %}
                    </h3>
                    <p>
                        {% trans 'До 31.07.2020 года для владельцев автомобилей премиум класса не старше 7 лет действует специальная программа трейд-ин. Размер бонуса зависит от выбранной модели Audi и суммируется к оценке стоимости вашего текущего автомобиля. Предложение по трейд-ин сочетается с любыми действующими акциями на новые автомобили Audi. Подробную информацию об условиях программы вы можете узнать у консультанта.' %}
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>
<section>
    <div class="container-fluid" style="padding: 0;">
        <div class="row">
            <div class="col-lg-12" style="padding: 0;">
                <form action="{% url 'json_filter_cars' %}" method="get" name="filter">
                    <div class="car-models-filter">
                        <ul>
                            {% for car in car_list %}
                                <li>
                                    <label class="checkbox-label">
                                        <input name="model" value="{{ car.model }}" type="checkbox">
                                        <span>{{ car.model }}</span>
                                    </label>
                                </li>
                            {% endfor %}

                            <li><button type="submit">{% trans 'Фильтровать' %}</button></li>
                        </ul>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="car-cards-container">
        {% for car in car_list %}
            <div class="car-card">
                <div class="car-img-outer">
                    <img class="car-img" src="{{ car.poster.url }}" alt="">
                    <div class="img-tile"></div>
                </div>
                <div class="car-title">
                    <h3>AUDI {{ car.model }} {{ car.line }}</h3>
                    <h5>{% trans 'от' %} {{ car.price }} {% trans 'руб. вкл. НДС' %}</h5>
                </div>
                <div class="car-button">
                    <a href="{{ car.get_absolute_url }}"><i class="fa fa-angle-right" aria-hidden="true"></i> {% trans 'Обзор' %}</a>
                </div>
            </div>
        {% endfor %}
    </div>
</section>

<script src="{% static 'js/lib/hogan.js' %}"></script>
<script src="{% static 'js/cars_filter.js' %}"></script>

{% endblock content %}

templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block title %}Корзина{% endblock title %}

{% block content %}
<section style="margin: 50px 0 50px 0;">
	<div class="container">
		<div class="row">
			<div class="col-lg-9" id="cartItems">

		    </div>
		    <div class="item-sidebar col-lg-3">
		    	<div class="item-sidebar-cart">
		    		<h1>{% trans 'Корзина покупок' %}</h1>
		    		<div class="item-sidebar-cart-body">
		    			<ul class="prices">
		    				<li>
		    					<label>{% trans 'Цена за товар' %}</label>
		    					<div class="pull-right products-price"><b>0.00₽</b></div>
		    				</li>
		    				<li>
		    					<label>{% trans 'Стоимость доставки' %}</label>
		    					<div class="pull-right"><b>400.00₽</b></div>
		    				</li>
		    			</ul>
		    			<ul class="total-price">
		    				<li>
		    					<label>{% trans 'Общая стоимость' %}</label>
		    					<div class="pull-right total-price-number"><b>0.00₽</b></div>
		    				</li>
		    			</ul>
		    			<div class="item-sidebar-cart-body-buttons pull-right">
		    				<button class="buy-button">{% trans 'Купить' %}</button>
		    			</div>
		    		</div>
		    		<div class="item-sidebar-cart-coupon">
		    			<h1>{% trans 'Использовать купон' %}</h1>
		    			<div class="item-sidebar-cart-coupon-body">
		    				<div class="coupon">
	        					<input type="text" placeholder="">
	        					<button>OK</button>
	        				</div>
		    			</div>
		    		</div>
		    	</div>
		    </div>
		</div>
	</div>
</section>

<script src="{% static 'js/cart.js' %}"></script>

{% endblock content %}

templates/detail_product.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block content %}
<section class="product_review">
    <div class="container">
        <div class="row">
            <div class="col-lg-5">
                <div class="product_img">
                    <img class="itemPicture" src="{{ product.picture }}" alt="31">
                </div>
            </div>
            <div class="col-lg-7">
                <div class="row">
                    <h3 class="itemTitle">{{ product.name }}</h3>
                </div>
                <div class="row price">
                    <h4>{% trans 'Цена' %}:&nbsp</h4>
                    <h4><span class="itemPrice">{{ product.price }},00₽</span></h4>
                </div>
                <div class="row">
                    <p class="text">
                        {{ product.description }}
                    </p>
                </div>
                <!--<div class="row">
                    <h5>Color</h5>
                    <p style="margin: auto;">{% trans 'Черный Серый Белый' %}</p>
                </div>
                <hr>
                <div class="row">
                    <h5>Size</h5>
                    <p style="margin: auto;">{% trans 'Имеется в разных размерах' %}</p>
                </div>-->
                <hr>
                <div class="row" style="margin-top: 25px;">
                    <input type="number" id="quantity" name="quantity" value="1" min="1" max="8">
                    <button class="basket" id="toCart" data-slug="{{ product.slug }}">{% trans 'В корзину' %}</button>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="product_info_tabs">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-md-4">
                <div>
                    <button class="info_btn" id="btn_more">{% trans 'Подробнее' %}</button>
                </div>
            </div>
            <div class="col-lg-4 col-md-4">
                <div>
                    <button class="info_btn" id="btn_feature">{% trans 'Характеристики' %}</button>
                </div>
            </div>
            <div class="col-lg-4 col-md-4">
                <div>
                    <button class="info_btn active_btn" id="reviews">{% trans 'Отзывы' %}</button>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="product_info_content prod_more_inf">
                <p class="text">
                    {% trans 'Рекомендованные параметры колесного диска могут немного отличаться для одной и той же машины, независимо от того, какой диск вы хотите установить на ваш автомобиль — стальной, литой или кованый. Но существует стандартная маркировка диска, которая выглядит, для примера, вот так: Поэтому если вы захотите измерить рулеткой внешний диаметр автомобильного диска, вы должны учитывать, что на самом деле его действительное значение чуть меньше. А чтобы перевести диаметр диска из сантиметров в дюймы, нужно разделить полученное значение на 2,54. У дисков с четырьмя крепёжными болтами (или гайками) PCD равно расстоянию между центрами дальних (противоположных) болтов или гаек.' %}
                </p>
            </div>
            <div class="product_info_content prod_feature">
                <table class="table table-striped">
                    <thead>
                      <tr>
                        <th scope="col">#</th>
                        <th scope="col">{% trans 'Имя' %}</th>
                        <th scope="col">{% trans 'Фамилия' %}</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <th scope="row">1</th>
                        <td>Mark</td>
                        <td>Otto</td>
                      </tr>
                      <tr>
                        <th scope="row">2</th>
                        <td>Jacob</td>
                        <td>Thornton</td>
                      </tr>
                      <tr>
                        <th scope="row">3</th>
                        <td>Larry</td>
                        <td>the Bird</td>
                      </tr>
                    </tbody>
                  </table>
            </div>
            <div class="product_info_content prod_review prod_tabs_active">
                {% if not product.reviews_set.all %}
                    <div class="row user_reviews">
                        <div class="row">
                            <div class="review_box">
                                <p class="text">{% trans 'Отзывов пока нет, новы можете стать первым!' %}</p>
                            </div>
                        </div>
                    </div>
                {% endif %}
                {% for review in product.reviews_set.all %}
                    <div class="row user_reviews">
                        <div class="row">
                            <h5>{{ review.name }}</h5>
                        </div>
                        <div class="row">
                            <div class="rating rating-review">
                                <input type="radio" {% if review.rating == 5 %}checked{% endif %} disabled ><label for="">
                                </label>
                                <input type="radio" {% if review.rating == 4 %}checked{% endif %} disabled ><label for="">
                                </label>
                                <input type="radio" {% if review.rating == 3 %}checked{% endif %} disabled ><label for="">
                                </label>
                                <input type="radio" {% if review.rating == 2 %}checked{% endif %} disabled ><label for="">
                                </label>
                                <input type="radio" {% if review.rating == 1 %}checked{% endif %} disabled ><label for="">
                                </label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="review_box">
                                <h6>{{ review.date }}</h6>
                                <p class="text">{{ review.text }}</p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
                <div class="row review_main_label">
                    <h4>{% trans 'Оставьте отзыв' %}</h4>
                </div>
                <form action="{% url 'add_review' product.slug %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="" style="margin: 0;"><strong>{% trans 'Оцените товар' %}</strong></label>
                        <div class="rating">
                            <input value="5" type="radio" name="rating" id="star1"><label for="star1">
                            </label>
                            <input value="4" type="radio" name="rating" id="star2"><label for="star2">
                            </label>
                            <input value="3" type="radio" name="rating" id="star3"><label for="star3">
                            </label>
                            <input value="2" type="radio" name="rating" id="star4"><label for="star4">
                            </label>
                            <input value="1" type="radio" name="rating" id="star5"><label for="star5">
                            </label>
                        </div>
                    </div>
                    <div class="form-group" style="margin-top: 40px;">
                      <label for="exampleFormControlSelect1">{% trans 'Имя' %}*</label>
                      <input class="form-control" name="name" type="text" placeholder="" required>
                    </div>
                    <div class="form-group">
                        <label for="exampleFormControlInput1">Email*</label>
                        <input type="email" name="mail" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com" required>
                      </div>
                    <div class="form-group">
                      <label for="exampleFormControlTextarea1">{% trans 'Ваш отзыв' %}</label>
                      <textarea name="text" class="form-control" id="exampleFormControlTextarea1" rows="3" required></textarea>
                    </div>
                    <div class="form-group" style="margin-top: 30px;">
                        <button type="submit" class="btn btn-primary">{% trans 'Отправить' %}</button>
                        <button type="reset" class="btn btn-primary" id="prod_reset_btn">{% trans 'Очистить' %}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

<div id="pop-out"></div>

<script src="{% static 'js/detail_product.js' %}"></script>
<script src="{% static 'js/product_tabs_info.js' %}"></script>
{% endblock content %}

templates/shop.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block title %}Магазин деталей{% endblock title %}

{% block content %}
<section>
    <div class="container">
        <div class="row filter">
            <div class="col-lg-6">
                <form action="{% url 'shop_search' %}" method="get">
                    <div class="search">
                        <input type="text" name="search_query" placeholder="{% trans 'Введите свой запрос' %}" required>
                        <button type="submit">{% trans 'Поиск' %}</button>
                    </div>
                </form>
            </div>
            <div class="col-lg-6">
                <form action="{% url 'shop_sort' %}" method="get">
                    <div class="sort-outer">
                        <div class="sort">
                            <select name="criterion" id="">
                                <option value="-rating">{% trans 'Самые популярные' %}</option>
                                <option value="price">{% trans 'По возвростанию цены' %}</option>
                                <option value="-price">{% trans 'По убыванию цены' %}</option>
                            </select>
                        </div>
                        <button type="submit">{% trans 'Сортировать' %}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="container">
        {% if not product_list %}
        <div>{% trans 'По вашему запросу' %} "{{ search_query }}" {% trans 'ничего не найдено' %}</div>
        {% endif %}
        {% for product in product_list %}
        <div class="row">
            <div class="item">
                <div class="col-lg-4">
                    <div class="outer-item-picture">
                        <img class="itemPicture" src="{{ product.picture }}" alt="">
                    </div>
                    <div class="rating rating-review rating-shop">
                        <div>
                            <input type="radio" {% if product.rating == 5 %}checked{% endif %} disabled ><label for="">
                            </label>
                            <input type="radio" {% if product.rating == 4 %}checked{% endif %} disabled ><label for="">
                            </label>
                            <input type="radio" {% if product.rating == 3 %}checked{% endif %} disabled ><label for="">
                            </label>
                            <input type="radio" {% if product.rating == 2 %}checked{% endif %} disabled ><label for="">
                            </label>
                            <input type="radio" {% if product.rating == 1 %}checked{% endif %} disabled ><label for="">
                            </label>
                        </div>
                    </div>
                </div>
                <div class="col-lg-8">
                    <h5><b class="itemTitle">{{ product.name }}</b></h5>
                    <h6><b>{% trans 'Цена' %}:</b>
                        <spin class="itemPrice">{{ product.price }}₽</spin>
                    </h6>
                    <ul class="icons">
                        <!--<li><i class="fa fa-cart-plus cartPlus" aria-hidden="true" data-slug="{{ product.slug }}"></i></li>-->
                        <!--<li><i class="fa fa-info-circle" aria-hidden="true"></i></li>-->
                        <li><a href="{{ product.get_absolute_url }}">
                            <button class="itemButton">{% trans 'Подробнее' %}</button>
                        </a></li>
                        <li>
                            <button class="itemButton cartPlus" data-slug="{{ product.slug }}">{% trans 'В корзину' %}</button>
                        </li>
                    </ul>
                    <hr>
                    <p class="mini-description">
                        {{ product.description }}
                    </p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="container">
        <div class="row">
            {% include 'include/pagination.html' %}
        </div>
    </div>
</section>

<div id="pop-out"></div>

<script src="{% static 'js/shop.js' %}"></script>

{% endblock content %}